name: Pipe1 Build and Push Docker Image

on:
  push:
    branches:
      - main  # La pipeline s'exécute lors des pushes sur la branche "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Étape 3 : Build l'image Docker
      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd-websrv1:latest

      # Étape 4 : Pousser l'image sur Docker Hub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd-websrv1:latest
